- name: Vars at task level
  hosts: localhost
  # Variables at parent or play level
  vars:
  - money: "5000 rs"
    land: "10 Acres"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY:{{money}}, LAND:{{land}}"
  - name: inherit values from play and add and overwrite
    vars:
    - money: "20000 rs"
      houses: "4 Houses"
    ansible.builtin.debug:
      msg: " Money:{{money}}, Land:{{land}} and HOUSES:{{houses}}"

